#!/usr/bin/env bash

#
# build-wget
#
# Build a standalone wget that supports TLS. This script is to be executed
# in a Docker container running the toltec-dev/base image. The resulting
# binary will be written to /root/wget
#

if [[ -z $SYSROOT ]]; then
    echo "This script must be executed in a Docker container running the"
    echo "toltec-dev/base image. The \$SYSROOT variable was not found."
    exit 1
fi

set -e

# Curl command with flags suitable for scripting, restricted to HTTPS
rsecurl() {
    curl --fail --silent --tlsv1.2 --proto '=https' "$@"
}

# Download and verify checksum
fetch() {
    rsecurl -o "$2" "$1"
    sha256sum -c <(echo "$3 $2") > /dev/null
}

cd /root

# Build Nettle
mkdir nettle-build
pushd nettle-build

fetch https://ftp.gnu.org/gnu/nettle/nettle-3.7.tar.gz nettle.tar.gz \
    f001f64eb444bf13dd91bceccbc20acbc60c4311d6e2b20878452eb9a9cec75a
tar --strip-components=1 -zxf nettle.tar.gz
rm nettle.tar.gz

./configure \
    --prefix="$SYSROOT/usr" \
    --host="$CHOST" \
    --enable-mini-gmp \
    --disable-shared \
    --disable-documentation \
    --disable-assembler
make -j $(nproc)
make install

popd
rm -r nettle-build

# Build GnuTLS
mkdir gnutls-build
pushd gnutls-build

fetch https://www.gnupg.org/ftp/gcrypt/gnutls/v3.7/gnutls-3.7.0.tar.xz gnutls.tar.xz \
    49e2a22691d252c9f24a9829b293a8f359095bc5a818351f05f1c0a5188a1df8
tar --strip-components=1 -Jxf gnutls.tar.xz
rm gnutls.tar.xz

./configure \
    --prefix="$SYSROOT/usr" \
    --host="$CHOST" \
    --disable-doc \
    --enable-static \
    --with-nettle-mini \
    --with-included-libtasn1 \
    --with-included-unistring \
    --without-p11-kit
make -j $(nproc)
make install

popd
rm -r gnutls-build

# Build wget
mkdir wget-build
pushd wget-build

fetch https://ftp.gnu.org/gnu/wget/wget-1.21.1.tar.gz wget.tar.gz \
    59ba0bdade9ad135eda581ae4e59a7a9f25e3a4bde6a5419632b31906120e26e
tar --strip-components=1 -zxf wget.tar.gz
rm wget.tar.gz

export GNUTLS_LIBS="-L$SYSROOT/usr/lib -Wl,-Bstatic -lgnutls -latomic -Wl,-Bdynamic -pthread  -lhogweed -lnettle"
./configure \
    --prefix="$SYSROOT/usr" \
    --host="$CHOST"
make -j $(nproc)

popd
mv wget-build/src/wget .
rm -r wget-build

# Strip symbols from the resulting binary
${CROSS_COMPILE}strip --strip-all wget
